"""
russell1000.py — Russell 1000 constituent snapshot (proxy).

Source: Financial Modeling Prep company-screener — top 1000 US-domiciled common
stocks (NYSE + Nasdaq, country=US, excludes ETFs/funds) ranked by market cap.
FMP exposes no Russell 1000 constituent endpoint and no free authoritative feed
is scrapable, so the scanner uses this top-1000-by-market-cap set as a Russell
1000 proxy. This static list is the offline fallback; scanner.py refreshes it
live from FMP on each run via get_russell1000_constituents().

Generated from live FMP data. Re-run the generator to refresh.
"""
from typing import List

RUSSELL1000: List[str] = [
    "NVDA", "AAPL", "GOOG", "GOOGL", "MSFT", "AMZN", "AVGO", "META", "SPCX", "TSLA",
    "BRK-B", "BRK-A", "LLY", "JPM", "MU", "WMT", "AMD", "V", "XOM", "JNJ",
    "MA", "CSCO", "INTC", "ABBV", "BAC", "COST", "AMAT", "CVX", "KO", "UNH",
    "CAT", "ORCL", "GE", "LRCX", "PG", "MS", "HD", "MRK", "GS", "NFLX",
    "PM", "RTX", "PLTR", "PANW", "DELL", "GEV", "WFC", "TXN", "KLAC", "C",
    "ANET", "AXP", "TMO", "IBM", "AMGN", "APH", "VZ", "CRWD", "MCD", "PEP",
    "WDC", "TMUS", "SCHW", "ABT", "NEE", "SNDK", "ADI", "TJX", "UNP", "BA",
    "BLK", "WELL", "DIS", "MRVL", "GILD", "DE", "T", "TBB", "QCOM", "BX",
    "SCCO", "IBKR", "CRM", "BKNG", "COP", "UBER", "PFE", "DHR", "PLD", "LMT",
    "BMY", "CVS", "APP", "COF", "SYK", "ISRG", "PH", "PGR", "SPGI", "VRTX",
    "SBUX", "GLW", "FTNT", "LOW", "NOW", "MO", "HWM", "SO", "SOMN", "SOJE",
    "BNY", "ADP", "GD", "SNOW", "EQIX", "PWR", "MCK", "PNC", "ADBE", "NET",
    "NEM", "MAR", "USB", "DUK", "CME", "DDOG", "CEG", "MNST", "CDNS", "CSX",
    "VRT", "MPC", "KKR", "MMM", "WM", "MRSH", "VLO", "FCX", "ABNB", "UPS",
    "CMI", "WMB", "HCA", "INTU", "ICE", "DASH", "RCL", "CMCSA", "PSX", "EMR",
    "MCO", "SHW", "ITW", "EPD", "CTAS", "ELV", "AMT", "ROST", "GM", "MDLZ",
    "EOG", "REGN", "ECL", "TRV", "HOOD", "BAM", "NOC", "HON", "NSC", "SNPS",
    "SPG", "SLB", "ORLY", "CI", "CL", "FDX", "APO", "APOS", "MSI", "HLT",
    "KMI", "TDG", "ET", "MPWR", "PCAR", "DLR", "AEP", "BSX", "CVNA", "ALL",
    "SATA", "URI", "WBD", "APD", "TGT", "HONA", "GWW", "AFL", "RSG", "TFC",
    "AJG", "HPE", "MET", "NKE", "FIX", "D", "BE", "COR", "PSA", "BKR",
    "BDX", "O", "MPLX", "NUE", "F", "TRGP", "SRE", "TER", "DAL", "OKE",
    "FANG", "OXY", "LITE", "AME", "LNG", "FAST", "KEYS", "CAH", "ROK", "CIEN",
    "ALAB", "EA", "NDAQ", "CTVA", "FITB-PM", "LHX", "COHR", "FITB", "STT", "CARR",
    "EBAY", "PYPL", "ETR", "ELC", "VST", "HEI", "EW", "ADSK", "AZO", "WAB",
    "AMP", "XEL", "XYZ", "CMG", "EXC", "PCG", "VTR", "FERG", "TTWO", "CBRS",
    "ODFL", "IDXX", "HUM", "AXON", "PFH", "CBRE", "PRU", "KDP", "YUM", "ARES",
    "WDAY", "FLEX", "AIG", "MSCI", "PAYX", "SYY", "LYV", "MCHP", "AU", "ED",
    "DHI", "RVMD", "ROP", "UAL", "CRWV", "A", "HIG", "IQV", "COIN", "NTRA",
    "PEG", "ADM", "CCL", "RKLB", "KVUE", "RKT", "IRM", "KMB", "STLD", "MTB",
    "WEC", "HSY", "KR", "EME", "NTAP", "PPLC", "VMC", "HBAN", "RJF", "EXPE",
    "UI", "CCI", "NTRS", "EQT", "MDLN", "VEEV", "JBL", "VG", "IR", "ZTS",
    "CASY", "CQP", "ON", "LVS", "MLM", "DXCM", "EXR", "ILMN", "MSTR", "STRC",
    "TPR", "CNC", "GEHC", "KHC", "RMD", "TDY", "EL", "AEE", "CFG", "BIIB",
    "TWLO", "DTE", "DTW", "SUNB", "CPNG", "VICI", "ATO", "FISV", "MTD", "NRG",
    "LPLA", "EIX", "ZM", "STRF", "DVN", "DG", "FE", "TPL", "CNP", "SYM",
    "DOV", "ALNY", "Q", "GFS", "OTIS", "XYL", "CINF", "MDB", "RDDT", "WRB",
    "CPRT", "HAL", "WSM", "ES", "CW", "AWK", "TEAM", "PPL", "RF", "AVB",
    "VRSN", "CRS", "DGX", "QSR", "P", "ATI", "FOXA", "JBHT", "RBLX", "VRSK",
    "LH", "RPRX", "CPAY", "HUBB", "HPQ", "CTSH", "EQR", "FCNCA", "SYF", "WAT",
    "FWONK", "PPG", "ZS", "DLTR", "PHM", "PFG", "KEY", "FICO", "SATS", "INCY",
    "ASTS", "WST", "AFRM", "TROW", "L", "OKTA", "BRO", "XPO", "CHD", "MKL",
    "DRI", "TCPA", "RL", "BURL", "FIS", "VLTO", "SN", "FOX", "CMSA", "FFIV",
    "FSLR", "CMS", "FWONA", "FCNCN", "STZ", "USFD", "ULTA", "LUV", "UTHR", "EXPD",
    "PKG", "DOW", "EXE", "MRNA", "GH", "IP", "OMC", "ROKU", "IOT", "WWD",
    "TW", "INSM", "NI", "SNA", "FTAI", "MTZ", "SOJD", "SOFI", "GPN", "RS",
    "TSN", "FITB-PA", "THC", "VTRS", "LEN", "SNX", "RBA", "BG", "SOJC", "EFX",
    "IFF", "MKSI", "ATHS", "CHTR", "WES", "CF", "SBAC", "MTSI", "STRD", "EVRG",
    "GIS", "CDW", "TOST", "DD", "RIVN", "ULS", "SMCI", "STRL", "LNT", "ROL",
    "BBY", "ZBH", "ENTG", "FLUT", "SSNC", "WY", "PFGC", "EWBC", "FTV", "PR",
    "BR", "FDXF", "STRK", "INVH", "DUKB", "BEN", "ITT", "RBC", "CHRW", "PAA",
    "BALL", "OVV", "HST", "KIM", "APG", "GPC", "NWS", "NLY", "LSCC", "IEX",
    "RGLD", "NBIX", "WPC", "AKAM", "WCC", "DKS", "TPG", "CRCL", "NVR", "NDSN",
    "CG", "CLH", "H", "DINO", "GEN", "JLL", "LAMR", "TSCO", "MEDP", "OWL",
    "VNOM", "PINS", "NTNX", "J", "PNFP", "PTC", "BBIO", "RGA", "RZC", "NWSA",
    "BWXT", "DVA", "MAA", "CDE", "CCZ", "SUI", "TLN", "OHI", "TRU", "DOC",
    "ARMK", "RBRK", "IESC", "SOLV", "COKE", "MLI", "TXT", "REG", "CSL", "MAIR",
    "LDOS", "GFL", "KKRS", "LII", "PAG", "SWK", "LECO", "CNA", "XELLL", "GL",
    "SITM", "COO", "MAS", "DTM", "CRBG", "ZBRA", "FNF", "ALB", "UHAL", "AIZN",
    "U", "AIZ", "HRL", "SGI", "DOCN", "MKC-V", "MKC", "RPM", "UNMA", "RRX",
    "TOL", "UNM", "TKO", "NXT", "SREA", "IONQ", "WMG", "BAX", "TXRH", "ARCC",
    "BF-B", "EXEL", "ECHO", "PS", "BIPI", "HAS", "DECK", "APA", "TRMB", "ALLY",
    "ELAN", "IVZ", "BWA", "EQH", "AVY", "DT", "HII", "ONTO", "GGG", "CCK",
    "AIT", "SJM", "WSO", "GLPI", "TYL", "PEN", "GWRE", "AUR", "ELS", "SF",
    "RVTY", "WBS", "VIRT", "BJ", "EVR", "UDR", "AMKR", "CORT", "SEIC", "MOG-A",
    "CR", "DRS", "PNW", "AGNC", "APC", "FHN", "HUBS", "NYT", "HUT", "ALGN",
    "DY", "FIVE", "AMH", "TTMI", "AA", "ARWR", "FIG", "SCI", "AFG", "BTSG",
    "CSGP", "DKNG", "GNRC", "BMRN", "CLX", "WTS", "DPZ", "AHR", "PODD", "BROS",
    "MANH", "WTRG", "KNX", "TECH", "EGP", "LFUS", "MUSA", "AXSM", "MGM", "W",
    "CRL", "OC", "BXP", "ERIE", "CPT", "AR", "JEF", "ARW", "UMBF", "EHC",
    "AEIS", "CACI", "SPXC", "SMTC", "GDDY", "JKHY", "DCI", "CGNX", "MDGL", "WTFC",
    "GSAT", "MOD", "GMED", "WMS", "VSAT", "ORI", "CART", "SUN", "DOCU", "AES",
    "AM", "SMMT", "ENSG", "BSY", "CFR", "WYNN", "ONB", "SFD", "MOH", "UHS",
    "SSB", "ZION", "IT", "AAL", "LTH", "KRYS", "GTLS", "SIRI", "PRI", "SANM",
    "CTRE", "RMBS", "BMNR", "BMNP", "GKOS", "R", "AYI", "HALO", "OGE", "HSIC",
    "GME", "SARO", "FLS", "AMG", "MGRB", "MGRD", "MGRE", "BRX", "FROG", "LINE",
    "QXO", "DAR", "CYTK", "LEVI", "BRKR", "TKR", "SOLS", "SAIL", "ALSN", "MSGS",
    "HL", "VICR", "CUBE", "RRC", "SWKS", "FDS", "CHWY", "ADC", "AVTR", "ACM",
    "VMI", "SAIA", "FRHC", "MTCH", "DDS", "EAT", "NUVL", "CIFR", "VIAV", "SNEX",
    "LLYVK", "NNN", "WLK", "VOYA", "ARE", "ESI", "PAYC", "OSK", "FCFS", "COLB",
    "CRNX", "BIO", "WAL", "PTGX", "HLI", "CHYM", "WULF", "TTC", "KTOS", "LNC",
    "FR", "PSKY", "FPS", "CBSH", "REXR", "TTEK", "IONS", "BOKF", "PRAX", "PBF",
    "ATR", "SYRE", "JXN", "NCLH", "KYMR", "OXLCG", "TTD", "LAD", "HESM", "RHP",
    "HQY", "BAH", "ZWS", "ZG", "AOS", "APGE", "DBX", "FORM", "IDA", "PCOR",
    "PRMB", "CNM", "Z", "ESE", "SFM", "KMX", "KNSL", "THG", "OSCR", "EMN",
    "AGX", "QRVO", "TGTX", "RGEN", "SNAP", "IMVT", "TTAN", "VLY", "CHRD", "IDCC",
    "CBC", "APLD", "NFG", "NEU", "PCVX", "SM", "TAP", "HXL", "ETSY", "PRH",
    "UGI", "LGN", "ALGM", "SSD", "MAC", "TEM", "AXTA", "FAF", "RIOT", "FSS",
    "TRNO", "POWL", "CMC", "CAVA", "AAOI", "AVAV", "PB", "PRS", "IBRX", "MHK",
    "LQDA", "CELH", "PCTY", "AWI", "HR", "MP", "MSA", "STAG", "AAON", "AVT",
    "PACS", "RAL", "GAP", "OMF", "LW", "MORN", "JBTM", "SLAB", "AGCO", "BLDR",
    "ACA", "AN", "GTES", "CHE", "VSXY", "VSCO", "JOBY", "MOS", "KEX", "FLR",
    "GLXY", "CAG", "COMP", "NOV", "MSM", "PL", "RYTM", "PATH", "ENS", "CMSD",
    "NE", "POOL", "EPRT", "OKLO", "ST", "FNB", "PLXS", "CMSC", "UBSI", "TMHC",
    "RSI", "CORZ", "COGT", "QBTS", "NPO", "ACT", "LUMN", "CLF", "CPB", "LEA",
    "M", "CRUS", "CWEN", "PPC", "INGM", "LNTH", "SWX", "FRVO", "MIRM", "APPF",
    "S", "GBCI", "TXNM", "JAN", "LOAR", "ECG", "KRMN", "BLLN", "WEX", "NAVN",
    "BLTE", "URBN", "GATX", "ENVA", "ERAS", "WFRD", "EXP", "DUOL", "CGON", "INGR",
    "AROC", "SNDR", "HOMB", "HWC", "RUSHA", "MTDR", "HIMS", "VCTR", "BYD", "MTG",
    "CROX", "MATX", "FND", "ADT", "CZR", "MXL", "TFX", "MIDD", "AUB", "LYFT",
]
